language: node_js
node_js:
- 4.4.3
services:

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
- CXX=g++-4.8
sudo: required
before_script:
- npm i
script:
- npm test
notifications:
  email:
    recipients:
    - Raziyeh.bazargan@gmail.com
    on_failure: change
    on_success: change
